[package]
edition = "2021"
name = "rp2040-ehv1"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[dependencies]

rp-pico = "0.9.0"
rp2040-hal = "0.10.2"
embedded-hal = "1.0.0"
panic-halt = "0.2.0"
cortex-m-rt = "0.7.3"
cortex-m = "0.7.7"